### PR TITLE
Bump Version: 6.16.0

### PR DESCRIPTION
**Pull request by rgoessl**

### CODE REVIEW

**Comment by ryantmer** [comment]
I'm not seeing a 6.16.0 tag to along with this - if you do the `npm version` thing specified in the README, it should do both! (No need for a PR with that method either)

**Comment by rgoessl** [comment]
Thanks @ryantmer I'll do that

**Comment by rgoessl** [comment]
@ryantmer It doesn't let me push my changes to master

**Comment by ryantmer** [comment]
d'oh, right - should work now, sorry about that!

**Comment by rgoessl** [comment]
It's worse now `Permission to Brightspace/d2l-hypermedia-constants.git denied to rgoessl`

**Comment by ryantmer** [comment]
Figured out offline, I forgot that `master` is a protected branch! v6.16.0 has now been released.

**Pull request closed without merging**
